### PR TITLE
Fix deprecated class constructor

### PR DESCRIPTION
**Pull request by vyants**
Library throw PHP Deprecated Warning at PHP7.

### CODE REVIEW

**Comment by danielhjames** [comment]
Hi @vyants, hi @kartik-v, there is a new community repo for mPDF where PHP 7 support is being worked on. You might want to check out issues such as https://github.com/mpdf/mpdf/issues/68 and the development branch https://github.com/mpdf/mpdf/commits/development Cheers!

**Comment by kartik-v** [comment]
@danielhjames thanks. Will check and update ...

**Comment by hscstudio** [comment]
thank awesome.. running well php7 #yii2

**Comment by massimilianomancini** [comment]
Hi @kartik-v,
any chance to merge the pull request of @vyants?

It is needed to fix warning constructor https://github.com/kartik-v/yii2-mpdf/issues/27

**Comment by kartik-v** [comment]
Will merge this... however am thinking of phasing this out slowly and directly using the mpdf repo suggested by @danielhjames for the yii2-mpdf extension.

**Comment by massimilianomancini** [comment]
Just tested and it works like a charm. 

> however am thinking of phasing this repo out slowly and directly using the mpdf repo suggested by @danielhjames for the yii2-mpdf extension.

Yes, it will be the right choice. I'm looking forward.

Thanks!

**Comment by Poolaidman** [comment]
Have you guys noticed an increase on speed when doing multiple page pdfs?

**Pull request merged**
